name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Enable Windows Terminal Environment
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
    - name: Install and Initialize Web Console Tunnel
      run: |
        choco install tmate -y
        Start-Process tmate -ArgumentList "-F" -RedirectStandardOutput "tmate.log"
        Start-Sleep -Seconds 15
        Write-Output "=========================================="
        Write-Output "YOUR WEB TERMINAL CONNECTION ADDRESS:"
        Get-Content tmate.log | Select-String "web:"
        Write-Output "=========================================="
    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -Seconds 60 }
