name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
    - name: Setup TCP Network Tunnel
      run: |
        $port = Get-Random -Minimum 12000 -Maximum 59000
        Invoke-WebRequest "https://github.com" -OutFile "frp.zip"
        tar -xf frp.zip
        $cfg = @"
        serverAddr = "vps.sekiro.org"
        serverPort = 7000
        [[proxies]]
        name = "rdp-$port"
        type = "tcp"
        localIP = "127.0.0.1"
        localPort = 3389
        remotePort = $port
        "@
        $cfg | Out-File .\frp_0.54.0_windows_amd64\frpc.toml -Encoding ascii
        Write-Output "=========================================="
        Write-Output "YOUR DIRECT PUBLIC TCP ADDRESS:"
        Write-Output "vps.sekiro.org:$port"
        Write-Output "=========================================="
        Start-Process .\frp_0.54.0_windows_amd64\frpc.exe -ArgumentList "-c .\frp_0.54.0_windows_amd64\frpc.toml" -WorkingDirectory .\frp_0.54.0_windows_amd64
    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -Seconds 60 }
